@startuml
    class Event{
    }

    class Conference{
    }

    class BoardMeeting{
    }

    class Person{
    }

    class Member{
    }

    class BoardMember{
    }

    class Location{
    }

    class AAUOC{
    }

    AAUOC o-- Location
    AAUOC o-- Event
    AAUOC o-- Person
    Location -- Event
    Event-- Member
    skinparam groupInheritance 2
        Event <|-- Conference
        Event <|-- BoardMeeting

    Member <|-- BoardMember
    Person <|-- Member
    BoardMeeting -- BoardMember
    Conference --Person

@enduml












