@startuml
    class Event{
    }
    class Conference{
    }
    class BoardMeeting{
    }
    class Location{
    }
    class AAUOC{
    }

    class Event{
    }
    class Conference{
    }
    class BoardMeeting{
    }

    class Person{
    }
    class Member{
    }
    class BoardMember{
    }

    Member <|-- BoardMember
    Person <|-- Member

    skinparam groupInheritance 2
        Event <|-- Conference
        Event <|-- BoardMeeting


    AAUOC o-- "0..*" Location
    AAUOC o-- "0..*" Event
    AAUOC o-- "0..*" Person

    Location "1" -- "0..*" Event: isLocated In

    Event "0..*" -- "0..*" Member: attendsTo


    BoardMeeting "0..*" -- "0..*" BoardMember: attendsTo
    Conference "0..*" -- "0..*" Person : attendsTo




@enduml




